mysky/config/routes.rb
Mysky::Application.routes.draw do

  devise_for :users
  root to: "users#index"

  resources :users do
    member do
      get 'profile' => 'users#profile'
    end
  end
  get 'users/search' => 'users#search'
  resources :myalbums
  resources :skyimages
  resources :friendships do
    collection do
      post 'add' => 'friendships#add'
    end
  end
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

end

mysky/app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

mysky/app/models/skyimage.rb
class Skyimage < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, {
    :styles => {
      :thumb => ["50x50#", :png],
      :medium => ["100x100#", :png],
      :large => ["300x300>", :png],
      :larger => ["600x600>", :png]
    },
    :convert_options => {
      :thumb => "-gravity Center -crop 50x50+0+0",
      :thumb => "-gravity Center -crop 100x100+0+0",
    }
  }

  validates_presence_of :title
  validates_presence_of :image


end

mysky/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :skyimages
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  has_attached_file :avatar, {
    :styles => {
      :thumb => ["50x50#", :png],
      :medium => ["100x100#", :png],
      :large => ["300x300>", :png]
    },
    :convert_options => {
      :thumb => "-gravity Center -crop 50x50+0+0",
      :thumb => "-gravity Center -crop 100x100+0+0",
    }
  }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :avatar

end

mysky/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) do |u|
        u.permit :name, :email, :password, :password_confirmation, :avatar
      end
      devise_parameter_sanitizer.for(:edit) do |u|
        u.permit :name, :email, :password, :password_confirmation, :avatar
      end
      devise_parameter_sanitizer.for(:account_update) do |u|
        u.permit :name, :email, :password, :password_confirmation, :current_password,:avatar
      end
    end
  protect_from_forgery with: :exception

  before_filter :set_search
  def set_search
    @search=User.search(params[:q])
  end

  before_filter :set_skyimage
  def set_skyimage
    @skyimage=Skyimage.new
  end
end

mysky/app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def index
    if !user_signed_in?
      redirect_to new_user_session_path
    else
      @friend = User.find(:all)
      @user = current_user
      @friends = Friendship.find(:all, :conditions => {:user_id => current_user.id})
      @friendss = current_user
      @friendship = current_user.friendships.all

    end
  end

  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    if @friendship.save
      flash[:notice] = "Added friend."
        redirect_to friendships_path
      else
        flash[:error] = "Unable to add friend."
        redirect_to friendships_path
      end
  end

  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    flash[:notice] = "Removed friendship."
    redirect_to friendships_path
  end

end

mysky/app/controllers/myalbums_controller.rb
class MyalbumsController < ApplicationController
  def index
    if !user_signed_in?
      redirect_to new_user_session_path
    else
      @profiles = current_user
    end
  end

end

mysky/app/controllers/skyimages_controller.rb
class SkyimagesController < ApplicationController
  def index

  end

  def new
    @skyimage = Skyimage.new
  end

  def create
    attr = params[:skyimage].permit(:image,:title,:location)
    @skyimage = Skyimage.new(attr)
    @skyimage.user_id = current_user.id
    if @skyimage.save
      redirect_to (:back), notice: "done uploading photo"
    else
      @skyimage = Skyimage.all
      redirect_to (:back), notice: "unable to upload photo"
    end
  end

  def show
    @my_skyimages = Skyimage.find(current_user.id)
  end

  def destroy
    @skyimages = Skyimage.find(params[:id])
    @skyimages.destroy
    redirect_to myalbums_path
  end
end

mysky/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if !user_signed_in?
      redirect_to new_user_session_path
    else
      @profile = current_user
      @friend = User.find(:all)
      @user = current_user
      @friends = Friendship.find(:all, :conditions => {:user_id => current_user.id})
      @friendss = current_user
      @friendship = current_user.friendships.all
    end
  end

  def new
  end

  def create
  end

  def show
    @searched_user = @search.result
  end

  def profile
    @user = current_user
    @searched_user = @search.result
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to @user
  end

  def search
    @searched_user = @search.result
  end
end

mysky/app/helpers/application_helper.rb
module ApplicationHelper
end

mysky/app/helpers/friendships_helper.rb
module FriendshipsHelper
end

mysky/app/helpers/myalbums_helper.rb
module MyalbumsHelper
end

mysky/app/helpers/skyimages_helper.rb
module SkyimagesHelper
end

mysky/app/helpers/users_helper.rb
module UsersHelper
end

mysky/app/views/friendships/index.html.erb
<h1>showing friends</h1>

<ul>
  <% for friendship in @user.friendships %>
    <p>
      <%= image_tag friendship.friend.avatar(:thumb) %>
      <%= friendship.friend.name %>
      (<%= link_to "remove", friendship, :method => :delete %>)
    </p>
  <% end %>
</ul>

mysky/app/views/layouts/_form.html.erb
<%= form_for(@skyimage) do |f| %>
  <div>
    <%= f.label "Choose your sky" %>
    <%= f.file_field :image %>
  </div></br>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div></br>

  <div>
    <%= f.label "Description" %>
    <%= f.text_field :body %>
  </div></br>

  <div>
    <%= f.label :location %>
    <%= f.text_field :location  %>
  </div></br>

  <%= f.submit "Post My Sky" %>

<% end %>

mysky/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mysky</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li><a href="/users/">Home</a></li>
              <li><a href="/myalbums/">My Album</a></li>

              <!--
              <form class="navbar-search">
                <div class="input-append">
                  <input type="text" class="span12" placeholder="Search for users">
                  <button type="submit" class="btn">
                    <i class="icon-search"></i>
                  </button>
                </div>
              </form>
              -->

            </ul>
            <ul class="nav pull-right">
              <% if current_user != nil %>
                <li>
                  <%= image_tag current_user.avatar(:thumb) %>
                </li>
                <li>
                  <%= link_to current_user.name, users_path %>
                </li>

              <%end%>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="nav nav-list span2">
      <div class="left-menu well">
        <li class="nav-header">Home</li>
        <li><a href="/users/"><i class="icon-home"></i>My Page</a></li>
        <li><a href="/myalbums"><i class="icon-book"></i>My Album</a></li>
        <li><a href="/friendships"><i class="icon-user"></i>My Friend</a></li>
        <li class="nav-header">Groups</li>
        <li><a href="/groups"><i class="icon-plus"></i>Add Group</a></li>
        <div class="user-controll">
          <%= link_to "Sign out",  destroy_user_session_path,  :method => :delete %><br>
          <%= link_to "Edit Profile", edit_user_registration_path %>
        </div>
      </div>
    </div>
    <div class="contents span7">
      <%= yield %>
    </div>
    <div class="right-menu span2">
      <% if current_user != nil %>
          <h4>Find your friend</h4>
        <div class = "friend-search-form well">
          <%= search_form_for @search,:url => {:controller => '/users', :action => 'search', :method => 'get'} do |f| %>
            <%= f.text_field :name_cont, :class => 'span12' %>
            <%= f.submit 'Search' %>
          <% end %>

        </div>

          <h4>Post your photo</h4>
        <div class = "post-img-form well">
          <%= form_for(@skyimage) do |f| %>
            <div>
              <%= f.label "Choose an image" %>
              <%= f.file_field :image %>
            </div></br>

            <div>
              <%= f.label :title %>
              <%= f.text_field :title, :class => 'span12' %>
            </div></br>

            <div>
              <%= f.label "Description" %>
              <%= f.text_field :body, :class => 'span12' %>
            </div></br>

            <div>
              <%= f.label :location %>
              <%= f.text_field :location, :class => 'span12' %>
            </div></br>

            <%= f.submit "Post My Sky" %>
          <% end %>
          <div id="notice">
            <% if notice == "done uploading photo" %>
              <div class="alert alert-success"><%= notice %></div>
            <% elsif notice == "unable to upload photo" %>
              <div class="alert alert-error"><%= notice %></div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
</body>


</html>


<script>
$(function() {
  setTimeout(function() {
    $('#notice').fadeOut("slow")
  }, 800);

  $('a[data-method="delete"]').on('ajax:success', function(e, data, status, xhr) {
    $('#post_'+data.post.id).fadeOut("slow");
  });
});
</script>

mysky/app/views/myalbums/index.html.erb
<h1>My Album</h1>
<% @profiles.skyimages.each do |skyimage| %>
  <%= link_to image_tag(skyimage.image(:large)),skyimage.image(:larger),:class=>"grouped_elements",:rel=>"group" %>
  <%= link_to 'Delete', skyimage, :confirm => 'Sure?',
                                  :method => :delete,
                                  :class => "btn btn-danger"
  %>
<% end %>

<script>
$(document).on('page:load',function() {
  setTimeout(function() {
    $('#notice').fadeOut("slow")
  }, 800);

  $('a[data-method="delete"]').on('ajax:success', function(e, data, status, xhr) {
    $('#post_'+data.post.id).fadeOut("slow");
  });
});
</script>

mysky/app/views/users/index.html.erb
<table class="table">
  <tbody>
    <% for friendship in @user.friendships %>
      <tr>
        <td class="avatar-img"><%= image_tag friendship.friend.avatar(:thumb) %></td>
        <td><%= link_to friendship.friend.name, profile_user_path(:id => friendship.friend.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

mysky/app/views/users/profile.html.erb
<div id="notice"><%= notice %></div>

<h1>
  <%= image_tag @user.avatar(:thumb) %>
  <%= @user.name %>
</h1>




<div id="album">
  <h2><%= "album" %></h2>
  <% @user.skyimages.each do |skyimage| %>
    <%= link_to image_tag(skyimage.image(:large)),skyimage.image(:larger),:class=>"grouped_elements",:rel=>"group" %>
  <% end %>
</div>

mysky/app/views/users/show.html.erb
<h1>Users found</h1>
<div id="notice"><%= notice %></div>

<% @searched_user.each do |user| %>
  <p>
  <%= image_tag user.avatar(:thumb) %>
  <%= link_to user.name, :controller => "users", :action => "profile", :id => user.id %>
  <%= link_to 'Add friend', friendships_path(:friend_id => user.id), :method => ':post', :class => "btn" %>
  </p>
<% end %>